#!/bin/bash

CACHE_INSTANCES_NUM=1
RELAY_INSTANCES_NUM=0
NAMING_FORMATE="l"


# "/opt/graphite/bin/"
pushd `dirname $0` > /dev/null
SCRIPT_PATH=$(pwd)
PARENT_SCRIPT_FOLDER=${PWD%/*}
CONFIG_FOLDER=$PARENT_SCRIPT_FOLDER/conf_default


echo "[INFO] ===== Starting Graphite ===== "

echo "[INFO] == Starting Carbon-Relay-NG =="

#python $SCRIPT_PATH/carbon_relay.py start $NAMING_FORMATE $RELAY_INSTANCES_NUM 
#$SCRIPT_PATH/carbon_relay.py start $NAMING_FORMATE $RELAY_INSTANCES_NUM 
$SCRIPT_PATH/carbon-relay-ng $CONFIG_FOLDER/carbon-relay-ng.ini

echo "[INFO] == Carbon-Relay Started =="

echo "[INFO] == Starting Carbon-Cache =="

python $SCRIPT_PATH/carbon_cache.py start $NAMING_FORMATE $CACHE_INSTANCES_NUM

echo "[INFO] == Carbon-Cache Started =="

echo "[INFO] ===== Finished ====="

echo "[NOTE] You should start graphite webapp server manually."